# Generated by Django 2.1.5 on 2019-04-03 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 2, 9, 54, 18449), verbose_name='date published'),
        ),
    ]
