# Generated by Django 2.1.5 on 2019-04-03 20:44

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190404_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 2, 14, 52, 270722), verbose_name='date published'),
        ),
    ]
